package com.testkshdata.dci.testdata.pojo;

public class MainLayers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column main_layers.layerId
     *
     * @mbggenerated
     */
    private Integer layerid;

    @Override
    public String toString() {
        return super.toString();
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column main_layers.visualId
     *
     * @mbggenerated
     */
    private Integer visualid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column main_layers.layerCname
     *
     * @mbggenerated
     */
    private String layercname;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column main_layers.layerEname
     *
     * @mbggenerated
     */
    private String layerename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column main_layers.layerDatas
     *
     * @mbggenerated
     */
    private String layerdatas;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column main_layers.layerBasicSet
     *
     * @mbggenerated
     */
    private String layerbasicset;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column main_layers.layerId
     *
     * @return the value of main_layers.layerId
     *
     * @mbggenerated
     */
    public Integer getLayerid() {
        return layerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column main_layers.layerId
     *
     * @param layerid the value for main_layers.layerId
     *
     * @mbggenerated
     */
    public void setLayerid(Integer layerid) {
        this.layerid = layerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column main_layers.visualId
     *
     * @return the value of main_layers.visualId
     *
     * @mbggenerated
     */
    public Integer getVisualid() {
        return visualid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column main_layers.visualId
     *
     * @param visualid the value for main_layers.visualId
     *
     * @mbggenerated
     */
    public void setVisualid(Integer visualid) {
        this.visualid = visualid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column main_layers.layerCname
     *
     * @return the value of main_layers.layerCname
     *
     * @mbggenerated
     */
    public String getLayercname() {
        return layercname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column main_layers.layerCname
     *
     * @param layercname the value for main_layers.layerCname
     *
     * @mbggenerated
     */
    public void setLayercname(String layercname) {
        this.layercname = layercname == null ? null : layercname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column main_layers.layerEname
     *
     * @return the value of main_layers.layerEname
     *
     * @mbggenerated
     */
    public String getLayerename() {
        return layerename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column main_layers.layerEname
     *
     * @param layerename the value for main_layers.layerEname
     *
     * @mbggenerated
     */
    public void setLayerename(String layerename) {
        this.layerename = layerename == null ? null : layerename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column main_layers.layerDatas
     *
     * @return the value of main_layers.layerDatas
     *
     * @mbggenerated
     */
    public String getLayerdatas() {
        return layerdatas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column main_layers.layerDatas
     *
     * @param layerdatas the value for main_layers.layerDatas
     *
     * @mbggenerated
     */
    public void setLayerdatas(String layerdatas) {
        this.layerdatas = layerdatas == null ? null : layerdatas.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column main_layers.layerBasicSet
     *
     * @return the value of main_layers.layerBasicSet
     *
     * @mbggenerated
     */
    public String getLayerbasicset() {
        return layerbasicset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column main_layers.layerBasicSet
     *
     * @param layerbasicset the value for main_layers.layerBasicSet
     *
     * @mbggenerated
     */
    public void setLayerbasicset(String layerbasicset) {
        this.layerbasicset = layerbasicset == null ? null : layerbasicset.trim();
    }
}